# zsh options
setopt AUTO_CD
setopt extended_glob
unsetopt CASE_GLOB

# PowerLevel9k theme
source "$ZDOTDIR/etc/powerlevel10k"

# enable git completions
autoload -Uz compinit && compinit

# aliases
source "$ZDOTDIR/aliases"

# local settings
source ~/.profile_local

# NVM
source "$ZDOTDIR/etc/nvm"