# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zsh options
setopt AUTO_CD
setopt extended_glob
unsetopt CASE_GLOB

# PowerLevel10k theme
source "$ZDOTDIR/etc/powerlevel10k"

# enable git completions
autoload -Uz compinit && compinit

# make completions case-insensitive
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# better history completions (only complete with matching commands)
# '\e[A' = up arrow, '\e[B' = down arrow
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

# aliases
source "$ZDOTDIR/aliases"

# local settings
if [ -f ~/.profile_local ]; then
    source ~/.profile_local
fi

# NVM
source "$ZDOTDIR/etc/nvm"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
fpath+=${ZDOTDIR:-~}/zsh_functions
